import pytest
from unittest.mock import patch, MagicMock
from awsbot_cli.workflow.jira_utils import update_jira_issue


@pytest.fixture
def mock_env(monkeypatch):
    """Ensure environment variables are set for testing."""
    monkeypatch.setenv("JIRA_EMAIL", "test@example.com")
    monkeypatch.setenv("JIRA_API_TOKEN", "fake-token")
    monkeypatch.setenv("JIRA_DOMAIN", "test.atlassian.net")


@patch("awsbot_cli.workflow.jira_utils.JIRA")
def test_update_jira_issue_success(mock_jira_class, mock_env):
    """Verify Jira is initialized correctly and the issue is updated with Wiki markup."""
    # 1. Setup Mocks
    mock_jira_instance = mock_jira_class.return_value
    mock_issue = MagicMock()
    mock_jira_instance.issue.return_value = mock_issue

    # 2. Execute
    result = update_jira_issue("PROJ-123", "Added new feature X")

    # 3. Assertions
    assert result is True

    # Check Initialization
    mock_jira_class.assert_called_once_with(
        server="https://test.atlassian.net",
        basic_auth=("test@example.com", "fake-token"),
    )

    # Check that the description contains Jira Wiki markup (h2. and ----)
    called_args = mock_issue.update.call_args[1]
    assert "h2. Automated Summary of Changes" in called_args["description"]
    assert "Added new feature X" in called_args["description"]
    assert "_Generated by AWSBOT CLI_" in called_args["description"]


def test_update_jira_issue_missing_env():
    """Verify function returns False and prints warning if env vars are missing."""
    with patch("os.getenv", return_value=None):
        result = update_jira_issue("PROJ-123", "summary")
        assert result is False


@patch("awsbot_cli.workflow.jira_utils.JIRA")
def test_update_jira_issue_error(mock_jira_class, mock_env):
    """Verify that exceptions from the JIRA library are caught gracefully."""
    mock_jira_instance = mock_jira_class.return_value
    mock_jira_instance.issue.side_effect = Exception("Jira is down")

    result = update_jira_issue("PROJ-123", "summary")
    assert result is False
