import os

from jira import JIRA


def update_jira_issue(jira_id, summary):
    email = os.getenv("JIRA_EMAIL")
    token = os.getenv("JIRA_API_TOKEN")
    domain = os.getenv("JIRA_DOMAIN")

    if not all([email, token, domain]):
        print("⚠️ Jira credentials missing.")
        return False

    try:
        # Initialize based on the signature you provided
        jira = JIRA(server=f"https://{domain}", basic_auth=(email, token))

        # Get the issue
        issue = jira.issue(jira_id)

        # Jira 'api/2' expects strings (Wiki Markup).
        # We use {code} blocks or simple headers to keep it readable.
        description_text = (
            "h2. Automated Summary of Changes\n\n"
            f"{summary}\n\n"
            "---- \n"
            " _Generated by AWSBOT CLI_"
        )

        # Use keyword arguments as defined in your provided update() signature
        issue.update(description=description_text)
        return True

    except Exception as e:
        print(f"❌ Jira Library Error: {e}")
        return False
